### ISSUE TITLE
Chevron animation

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify-site-2020#181]
![image](https://user-images.githubusercontent.com/12690/91736584-325cc980-ebae-11ea-8bc7-f2bdedb839a5.png)

I would like the chevron to animate when you click open the accordion.

**Comment by josefaidt** [comment]
Hi @Wolfr 👋  I'd like to help out with this one. Where can I find this menu on the site?

**Comment by Wolfr** [comment]
Cool! 👍

If you open the website on a mobile mobile and click the hamburger menu you can see the chevrons.

For inspiration, maybe you can check the animation code in this new Svelte UI framework: 
https://illright.github.io/attractions/docs/components/accordion
